i1 = 9999999999
i2 = 1234567890
f1 = 12345678.9
f2 = 0.0
b1 = True
b2 = False
#s1 = "Virat Kohli hit a massive six"
s1 = "1010101010"
#s2 = "if"
s2 = "987654321"
print(i1)
print(i2)
print(f1)
print(f2)
print(b1)
print(b2)
print(s1)
print(s2)
print(type(i1))
print(type(i2))
print(type(f1))
print(type(f2))
print(type(b1))
print(type(b2))
print(type(s1))
print(type(s2))
modified_float_i1=float(i1)
modified_bool_i1=bool(i1)
modified_str_i1=str(i1)
modified_float_i2=float(i2)
modified_bool_i2=bool(i2)
modified_str_i2=str(i2)
modified_int_f1=int(f1)
modified_bool_f1=bool(f1)
modified_str_f1=str(f1)
modified_int_f2=int(f2)
modified_bool_f2=bool(f2)
modified_str_f2=str(f2)
modified_int_b1=int(b1)
modified_float_b1=float(b1)
modified_str_b1=str(b1)
modified_int_b2=int(b2)
modified_float_b2=float(b2)
modified_str_b2=str(b2)
modified_int_s1=int(s1)
modified_bool_s1=bool(s1)
modified_float_s1=float(s1)
modified_int_s2=int(s2)
modified_bool_s2=bool(s2)
modified_float_s2=float(s2)
print("The value of i1 modified to float is "+str(modified_float_i1)+" and its type is "+str(type(modified_float_i1)))
print("The value of i1 modified to bool is "+str(modified_bool_i1)+" and its type is "+str(type(modified_bool_i1)))
print("The value of i1 modified to str is "+str(modified_str_i1)+" and its type is "+str(type(modified_str_i1)))
print("The value of i2 modified to float is "+str(modified_float_i2)+" and its type is "+str(type(modified_float_i2)))
print("The value of i2 modified to bool is "+str(modified_bool_i2)+" and its type is "+str(type(modified_bool_i2)))
print("The value of i2 modified to str is "+str(modified_str_i2)+" and its type is "+str(type(modified_str_i2)))
print("The value of f1 modified to int is "+str(modified_int_f1)+" and its type is "+str(type(modified_int_f1)))
print("The value of f1 modified to bool is "+str(modified_bool_f1)+" and its type is "+str(type(modified_bool_f1)))
print("The value of f1 modified to str is "+str(modified_str_f1)+" and its type is "+str(type(modified_str_f1)))
print("The value of f2 modified to int is "+str(modified_int_f2)+" and its type is "+str(type(modified_int_f2)))
print("The value of f2 modified to bool is "+str(modified_bool_f2)+" and its type is "+str(type(modified_bool_f2)))
print("The value of f2 modified to str is "+str(modified_str_f2)+" and its type is "+str(type(modified_str_f2)))
print("The value of b1 modified to int is "+str(modified_int_b1)+" and its type is "+str(type(modified_int_b1)))
print("The value of b1 modified to float is "+str(modified_float_b1)+" and its type is "+str(type(modified_float_b1)))
print("The value of b1 modified to str is "+str(modified_str_b1)+" and its type is "+str(type(modified_str_b1)))
print("The value of b2 modified to int is "+str(modified_int_b2)+" and its type is "+str(type(modified_int_b2)))
print("The value of b2 modified to float is "+str(modified_float_b2)+" and its type is "+str(type(modified_float_b2)))
print("The value of b2 modified to str is "+str(modified_str_b2)+" and its type is "+str(type(modified_str_b2)))
print("The value of s1 modified to int is "+str(modified_int_s1)+" and its type is "+str(type(modified_int_s1)))
print("The value of s1 modified to float is "+str(modified_float_s1)+" and its type is "+str(type(modified_float_s1)))
print("The value of s1 modified to bool is "+str(modified_bool_s1)+" and its type is "+str(type(modified_bool_s1)))
print("The value of s2 modified to int is "+str(modified_int_s2)+" and its type is "+str(type(modified_int_s2)))
print("The value of s2 modified to float is "+str(modified_float_s2)+" and its type is "+str(type(modified_float_s2)))
print("The value of s2 modified to bool is "+str(modified_bool_s2)+" and its type is "+str(type(modified_bool_s2)))
